
x = input("Com qual valor você deseja construir o pinheiro? ")
print("       "+x)
print("      "+x+x+x)
print("     "+x+x+x+x+x)
print("    "+x+x+x+x+x+x+x)
print("   "+x+x+x+x+x+x+x+x+x)
print(" "+x+x+x+x+x+x+x+x+x+x+x+x+x)
print(""+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x)
print("      "+x+x)
print("      "+x+x)
print("     "+x+x+x+x)
